---
  # Remove the default nginx site/init.d setup.
  # Really, obliterate it.

  - name: Remove the default nginx site
    file: dest=/etc/nginx/conf.d/default.conf state=absent

  - name: Remove the default nginx ssl site
    file: dest=/etc/nginx/conf.d/example_ssl.conf state=absent

  - name: Remove the default nginx sites-enabled entry
    file: dest=/etc/nginx/sites-enabled/default state=absent

  - name: Remove the default nginx sites-available entry
    file: dest=/etc/nginx/sites-available/default state=absent

  - name: Stop init.d from starting nginx at boot
    shell: update-rc.d -f nginx disable

  - name: Stop the running default nginx service
    shell: service nginx stop

  - name: Delete the init.d entry, we don't need it
    shell: rm /etc/init.d/nginx
